<?php

namespace ArticlesBundle\Repository;

/**
 * cirquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cirquesRepository extends \Doctrine\ORM\EntityRepository
{
}
