<?php

namespace ArticlesBundle\Repository;

/**
 * PlagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlagesRepository extends \Doctrine\ORM\EntityRepository
{
}
