<?php

namespace ArticlesBundle\Repository;

/**
 * VolcanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolcanRepository extends \Doctrine\ORM\EntityRepository
{
}
